[project]
name = "syntesa-lab-attendance-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.14.0",
    "fastapi[standard]>=0.128.6",
    "sqlmodel>=0.0.32",
    "tqdm>=4.67.3",
]
